name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Archive artifacts
      run: tar cvfz drcloud.tar.gz build/*

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      run: aws s3 cp drcloud.tar.gz s3://elephantcodingclub/archive/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Deploy with AWS CodeDeploy
      run: aws deploy create-deployment \
        --application-name githubaction-elephant \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name githubaction-elephant-group \
        --s3-location bucket=elephantcodingclub,bundleType=tgz,key=archive/drcloud.tar.gz
